### ISSUE TITLE
Pattern in editor?

### ISSUE THREAD

**Issue by labs-dlugo** [Futsy/vscode-headerpatterns#1]
Is it possible to have a pattern background for the editor such as this:

![image](https://user-images.githubusercontent.com/32064271/68339080-3a48fb80-00ba-11ea-8cf6-1aa43eece9f4.png)

(Image from text editor bundled with ubuntu 19.04).

**Comment by Futsy** [comment]
Hey,

I've just added this option to the [new version](https://marketplace.visualstudio.com/items?itemName=futs.headerpatterns) ([1.4.0](https://github.com/Futsy/vscode-headerpatterns/commit/2f68e58f15f1e1c483d195e7968fb733c69a782a)). In the new version there are two new settings to change which will allow you to do it:

- **editorPattern** to pick any background pattern for the editor, I've set the default to GraphPaper which most closely resembles the image (see [this link for alternative patterns](https://marketplace.visualstudio.com/items?itemName=futs.headerpatterns)).
- **fillColorEditor** to change the color of the pattern lines.

Screenie of what it looks like with dark settings:

![](https://imgur.com/wrKvmh7.png)

**Comment by calogxro** [comment]
this doesn't work for me
