### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by eykamp** [Futsy/vscode-headerpatterns#4]
Hi -- I've uninstalled the extension, and I keep seeing the last pattern I used appear in VSCode.  The issue persists even after reinstalling VSCode (though not initially, immediately after reinstall the pattern is gone, but after the next restart, it's back).

Any idea how I can completely eradicate the pattern?

Thanks!

**Comment by Futsy** [comment]
Hey,

You can completely remove it by removing the CSS code from the file in the appdata:

 AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.css

The custom added code should look like this:

```
/*css-pattern-start*/
/*headerpatterns.ver.1.0*/

...

/*css-pattern-end*/
```

**Comment by eykamp** [comment]
Ok, I've done that.  Interesting, the urls in that block were already set to "" (which matches the fact that after an initial reinstall there is no background image).  If it reappears after my next restart I'll try it again.

Thanks!

On Fri, May 13, 2022, at 10:33, Floris Velleman wrote:
> 
> 
> Hey,
> 
> You can completely remove it by removing the CSS code from the file in the appdata:
> 
> AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.css
> 
> The custom added code should look like this:
> 
> `/*css-pattern-start*/
> /*headerpatterns.ver.1.0*/
> 
> ...
> 
> /*css-pattern-end*/
`
